### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-package-deps'

### ISSUE THREAD

**Issue by rathinavital** [AtomLinter/linter-phpcs#311]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [linter-phpcs](https://github.com/AtomLinter/linter-phpcs) package 1.6.8

### Stack Trace

Uncaught Error: Cannot find module 'atom-package-deps'

```
At module.js:472

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at installLinterPhpcsDeps (/packages/linter-phpcs/lib/main.js:119:9)
```

### Commands

```
```

### Non-Core Packages

```
aligner-css 1.2.0 
aligner-php 1.0.0 
aligner-scss 1.1.0 
atom-alignment 0.12.1 
atom-beautify 0.29.16 
atom-html-templates 0.1.3 
atom-name-that-color 0.1.3 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
color-picker 2.2.3 
compare-files 0.8.0 
docblockr 0.9.1 
double-tag 0.4.0 
emmet 2.4.3 
emmet-simplified 2.5.0 
file-type-icons 1.3.3 
jquery-snippets 11.0.0 
linter-phpcs 1.6.8 
one-dark-matte-syntax 0.0.7 
project-manager 3.3.3 
simple-drag-drop-text 0.3.1 
```

**Comment by Arcanemagus** [comment]
This is usually fixed by a re-install or update. Let me know if you are still having issues after updating to v1.6.10.
